name: Deploy Expense-Ease

on:
  push:
    branches: [ dev ]
  workflow_dispatch:
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm i

    # - name: Run tests
    #   run: npm test

    - name: Run tests
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_NAME_TEST: ${{ secrets.DB_NAME_TEST }}
        DB_HOST: ${{ secrets.DB_HOST }}
        NODE_ENV: test
      run: npm test



    - name: Deploy to production server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.BACKEND_HOST }}
        username: ${{ secrets.BACKEND_USERNAME }}
        key: ${{ secrets.BACKEND_PRIVATE_KEY }}
        script: |
          ~/start-expense-ease-backend.sh